name: Chocolatey Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  chocolatey:
    name: Deploy
    runs-on: windows-latest
    if: github.repository == 'gnpaone/MSEdgeRedirect'
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set Checksum
        run: |
          filename="MSEdgeRedirect_x86.exe"
          url="https://drive.google.com/uc?id=1Atm8W0w1CFxF1u0L1i0FxQgObcKQlbXg&export=download&confirm=t"
          sed -i "s#{URL32}#${url}#g" "Assets/Choco/MSEdgeRedirect/tools/chocolateyinstall.ps1"
          curl -sSL "${url}" -o "Assets/Choco/${filename}"
          md5=$(cat "Assets/Choco/${filename}" | md5sum -)
          sed -i "s/{MD5CHECKSUM32}/${md5:0:32}/g" "Assets/Choco/MSEdgeRedirect/tools/chocolateyinstall.ps1"
          filename="MSEdgeRedirect.exe"
          url="https://drive.google.com/uc?id=1NAyQ-60KuK5SdzzWcgxEeyyWpHXiqn0p&export=download&confirm=t"
          sed -i "s#{URL64}#${url}#g" "Assets/Choco/MSEdgeRedirect/tools/chocolateyinstall.ps1"
          curl -sSL "${url}" -o "Assets/Choco/${filename}"
          md5=$(cat "Assets/Choco/${filename}" | md5sum -)
          sed -i "s/{MD5CHECKSUM64}/${md5:0:32}/g" "Assets/Choco/MSEdgeRedirect/tools/chocolateyinstall.ps1"
      - name: Set Version
        id: version
        run: |
          version="0.6.3.1"
          echo "::set-output name=nuget::$version"
          sed -i "s/{VERSION}/${version}/g" "Assets/Choco/MSEdgeRedirect/msedgeredirect.nuspec"
      - name: Pack Release
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack Assets/Choco/MSEdgeRedirect/msedgeredirect.nuspec --outputdirectory Assets/Choco/MSEdgeRedirect
      - name: Release
        uses: actions/upload-artifact@v2
        with:
          name: choco
          path: |
            Assets/Choco/MSEdgeRedirect/msedgeredirect.${{ steps.version.outputs.nuget }}.nupkg
          if-no-files-found: error
