name: Submit MSEdgeRedirect to winget

on:
  workflow_dispatch:

jobs:
  winget-bump:
    name: mser winget
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - name: winget test
        uses: actions/upload-artifact@v2
        with:
          name: winget
          path: |
            ${{ github.event_path }}
          if-no-files-found: error
      - name: winget log
        run: |
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $asset = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect_x86.exe'
          $asset64 = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect.exe'
          $version = $github.release.tag_name
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          ./wingetcreate.exe settings
          cd $env:LOCALAPPDATA\Microsoft\WinGet\Settings
          $pathToJson = "settings.json"
          $a = Get-Content $pathToJson | ConvertFrom-Json
          $a.WindowsPackageManagerRepository.owner = "gnpaone"
          $a | ConvertTo-Json | set-content $pathToJson
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: winget-settings
          path: |
            wingetcreate.exe
            $env:LOCALAPPDATA\Microsoft\WinGet\Settings\settings.json
          if-no-files-found: error
