name: Submit MSEdgeRedirect to winget

on:
  workflow_dispatch:

jobs:
  winget-bump:
    name: mser winget
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - name: winget test
        uses: actions/upload-artifact@v2
        with:
          name: winget
          path: |
            ${{ github.event_path }}
          if-no-files-found: error
      - name: winget log
        run: |
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $asset = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect_x86.exe'
          $asset64 = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect.exe'
          $version = $github.release.tag_name
          curl https://github.com/microsoft/winget-create/releases/latest/download/wingetcreate-self-contained.exe -O wingetcreate-self-contained.exe
          ./wingetcreate-self-contained.exe settings
          $pathToJson = "$env:LOCALAPPDATA\Microsoft\WindowsPackageManagerManifestCreator\settings.json"
          $a = Get-Content $pathToJson | ConvertFrom-Json
          $a.WindowsPackageManagerRepository.owner = "gnpaone"
          $a | ConvertTo-Json | set-content $pathToJson
          Copy-Item -Path $env:LOCALAPPDATA\Microsoft\WindowsPackageManagerManifestCreator\settings.json -Destination C:\settings.json -PassThru
          ./wingetcreate-self-contained.exe update rcmaehl.MSEdgeRedirect --urls $asset64.browser_download_url $asset.browser_download_url -v $version -o manifests -t "${{ secrets.MSEdgeRedirect_PAT }}" --submit
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: winget-settings
          path: |
            C:\settings.json
          if-no-files-found: error
