name: Submit MSEdgeRedirect to winget

on:
  workflow_dispatch:

jobs:
  winget-bump:
    name: mser winget
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - name: winget test
        uses: actions/upload-artifact@v2
        with:
          name: winget
          path: |
            ${{ github.event_path }}
          if-no-files-found: error
      - name: winget log
        run: |
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $asset = $github.release.assets | Where-Object -Property name -match 'MSEdgeRedirect[\d\.]*.exe'
          $version = $github.release.tag_name
          echo $version
          echo ${asset}
          echo ${asset.browser_download_url}
